list=[1,2,3,"hello",4]
print(list)
print(list.insert(0,5))
print(list)
print(list.remove(3))
print(list*2)
dict={1:"one",2:"two",3:"three"}
print(dict)
dict2={5:"five"}
print(dict.update(dict2))
print(dict.pop(3))
print(dict)
dict[4]="four"
print(dict)
set={1,2,3,4}
print(set)
set.update(("afternoon","good"))
print(set)
set.remove("good")
print(set)
set.add(10)
print(set)
